window.siteData = {
  siteName: "向老师的FitPulse Lab",
  siteTagline: "健身科普内容站",
  heroEyebrow: "Strength. Engine. Recovery.",
  heroTitle: "把训练、恢复和营养，讲成真正能改变习惯的知识。",
  heroDescription:
    "围绕力量训练、有氧运动、科学原理、运动康复和营养指南，持续整理更清晰、更可信、更容易执行的健身科普内容。",
  footerText: "训练不是碎片化打卡，而是长期认知与习惯的建立。",
  categories: [
    {
      id: "strength",
      name: "力量训练",
      accent: "ember",
      image: "./images/strength-category-cover.png",
      description: "围绕动作技术、训练计划、容量安排和渐进超负荷，帮助读者真正理解怎么练得更稳、更强。",
    },
    {
      id: "cardio",
      name: "有氧运动",
      accent: "volt",
      image: "./images/cardio-category-cover.png",
      description: "关注心肺能力、跑步节奏、间歇训练和日常耐力表现，让有氧不再只是“多跑一点”。",
    },
    {
      id: "science",
      name: "科学原理",
      accent: "glacier",
      image: "./images/science-category-cover.png",
      description: "拆解训练适应、恢复窗口、能量系统和长期进步背后的核心逻辑。",
    },
    {
      id: "rehab",
      name: "运动康复",
      accent: "lime",
      image: "./images/rehab-category-cover.png",
      description: "面向肩、膝、髋和脊柱常见问题，整理动作控制、活动度与恢复策略。",
    },
    {
      id: "nutrition",
      name: "营养指南",
      accent: "sun",
      image: "./images/nutrition-category-cover.png",
      description: "聚焦热量、蛋白质、补水、电解质和日常饮食结构，让营养建议更容易执行。",
    },
  ],
  posts: [
    {
      id: "strength-article-001",
      title: "力量训练图文标题示例",
      category: "strength",
      type: "article",
      summary: "这里放力量训练类图文摘要。以后你可以替换成动作讲解、计划安排或常见误区内容。",
      content: [
        {
          heading: "第一段小标题",
          body: "这里填写第一段正文内容，适合讲动作关键点、训练逻辑或场景说明。",
        },
        {
          heading: "第二段小标题",
          body: "这里填写第二段正文内容，适合拆解常见错误、负荷安排或训练顺序。",
        },
        {
          heading: "第三段小标题",
          body: "这里填写第三段正文内容，适合作为总结、建议或实际执行方式。",
        },
      ],
      takeaways: ["重点提示一", "重点提示二", "重点提示三"],
      image: "./images/strength-category-cover.png",
      tags: ["力量训练", "图文模板", "动作技术"],
      featured: true,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-strength-article-001",
    },
    {
      id: "strength-video-001",
      title: "力量训练视频标题示例",
      category: "strength",
      type: "video",
      summary: "这里放力量训练类视频摘要。以后你只需要把标题、摘要和视频链接替换成自己的内容。",
      image: "./images/strength-category-cover.png",
      tags: ["力量训练", "视频模板", "训练示范"],
      featured: false,
      readTime: "视频",
      ctaLabel: "打开视频",
      ctaUrl: "https://example.com/video/strength-template",
    },
    {
      id: "cardio-article-001",
      title: "有氧运动图文标题示例",
      category: "cardio",
      type: "article",
      summary: "这里放有氧运动类图文摘要。适合写跑步节奏、耐力安排或入门训练建议。",
      content: [
        {
          heading: "第一段小标题",
          body: "这里填写有氧主题的第一段正文，比如训练节奏、频率安排或动作基础。",
        },
        {
          heading: "第二段小标题",
          body: "这里填写第二段正文，比如强度判断、常见误区或阶段进阶方式。",
        },
      ],
      takeaways: ["重点提示一", "重点提示二"],
      image: "./images/cardio-category-cover.png",
      tags: ["有氧运动", "图文模板", "耐力训练"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-cardio-article-001",
    },
    {
      id: "cardio-video-001",
      title: "有氧运动视频标题示例",
      category: "cardio",
      type: "video",
      summary: "这里放有氧运动类视频摘要。可以替换成跑步、跳绳、间歇训练或心肺训练视频链接。",
      image: "./images/cardio-category-cover.png",
      tags: ["有氧运动", "视频模板", "心肺训练"],
      featured: true,
      readTime: "视频",
      ctaLabel: "打开视频",
      ctaUrl: "https://example.com/video/cardio-template",
    },
    {
      id: "science-article-001",
      title: "科学原理图文标题示例",
      category: "science",
      type: "article",
      summary: "这里放科学原理类图文摘要。适合写训练适应、恢复逻辑、负荷管理等科普内容。",
      content: [
        {
          heading: "第一段小标题",
          body: "这里填写科学原理内容的第一段正文，适合讲清核心概念或基本逻辑。",
        },
        {
          heading: "第二段小标题",
          body: "这里填写第二段正文，适合解释因果关系、适应机制或误区来源。",
        },
        {
          heading: "第三段小标题",
          body: "这里填写第三段正文，适合落到实际建议或更易执行的理解方式。",
        },
      ],
      takeaways: ["重点提示一", "重点提示二", "重点提示三"],
      image: "./images/science-category-cover.png",
      tags: ["科学原理", "图文模板", "训练适应"],
      featured: false,
      readTime: "5 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-science-article-001",
    },
    {
      id: "science-video-001",
      title: "科学原理视频标题示例",
      category: "science",
      type: "video",
      summary: "这里放科学原理类视频摘要。适合连接训练原理讲解、误区分析或恢复机制视频。",
      image: "./images/science-category-cover.png",
      tags: ["科学原理", "视频模板", "恢复机制"],
      featured: false,
      readTime: "视频",
      ctaLabel: "打开视频",
      ctaUrl: "https://example.com/video/science-template",
    },
    {
      id: "rehab-article-001",
      title: "运动康复图文标题示例",
      category: "rehab",
      type: "article",
      summary: "这里放运动康复类图文摘要。适合写肩、膝、髋、脊柱相关的控制、活动度或恢复思路。",
      content: [
        {
          heading: "第一段小标题",
          body: "这里填写运动康复主题的第一段正文，适合描述常见问题或恢复前提。",
        },
        {
          heading: "第二段小标题",
          body: "这里填写第二段正文，适合写恢复动作思路、控制重点或节奏安排。",
        },
        {
          heading: "第三段小标题",
          body: "这里填写第三段正文，适合总结恢复建议和日常执行方式。",
        },
      ],
      takeaways: ["重点提示一", "重点提示二", "重点提示三"],
      image: "./images/rehab-category-cover.png",
      tags: ["运动康复", "图文模板", "恢复策略"],
      featured: true,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-rehab-article-001",
    },
    {
      id: "rehab-video-001",
      title: "运动康复视频标题示例",
      category: "rehab",
      type: "video",
      summary: "这里放运动康复类视频摘要。以后可以直接换成肩、膝、髋、腰背相关的视频链接。",
      image: "./images/rehab-category-cover.png",
      tags: ["运动康复", "视频模板", "恢复训练"],
      featured: false,
      readTime: "视频",
      ctaLabel: "打开视频",
      ctaUrl: "https://example.com/video/rehab-template",
    },
    {
      id: "nutrition-article-001",
      title: "营养指南图文标题示例",
      category: "nutrition",
      type: "article",
      summary: "这里放营养指南类图文摘要。适合写蛋白质、补水、进食节奏或减脂增肌饮食建议。",
      content: [
        {
          heading: "第一段小标题",
          body: "这里填写营养主题的第一段正文，适合说明基础原则或常见疑问。",
        },
        {
          heading: "第二段小标题",
          body: "这里填写第二段正文，适合展开执行建议、饮食场景或频率安排。",
        },
      ],
      takeaways: ["重点提示一", "重点提示二"],
      image: "./images/nutrition-category-cover.png",
      tags: ["营养指南", "图文模板", "饮食结构"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-nutrition-article-001",
    },
    {
      id: "nutrition-video-001",
      title: "营养指南视频标题示例",
      category: "nutrition",
      type: "video",
      summary: "这里放营养指南类视频摘要。以后你可以替换成饮食建议、蛋白质科普或补水相关视频链接。",
      image: "./images/nutrition-category-cover.png",
      tags: ["营养指南", "视频模板", "饮食建议"],
      featured: false,
      readTime: "视频",
      ctaLabel: "打开视频",
      ctaUrl: "https://example.com/video/nutrition-template",
    },
  ],
};
