window.siteData = {
  siteName: "向老师的FitPulse Lab",
  siteTagline: "健身科普内容站",
  heroEyebrow: "Strength. Engine. Recovery.",
  heroTitle: "把训练、恢复和营养，讲成真正能改变习惯的知识。",
  heroDescription:
    "围绕力量训练、有氧运动、科学原理、运动康复和营养指南，持续整理更清晰、更可信、更容易执行的健身科普内容。",
  footerText: "训练不是碎片化打卡，而是长期认知与习惯的建立。",
  categories: [
    {
      id: "strength",
      name: "力量训练",
      accent: "ember",
      description: "围绕动作技术、训练计划、容量安排和渐进超负荷，帮助读者真正理解怎么练得更稳、更强。",
    },
    {
      id: "cardio",
      name: "有氧运动",
      accent: "volt",
      description: "关注心肺能力、跑步节奏、间歇训练和日常耐力表现，让有氧不再只是“多跑一点”。",
    },
    {
      id: "science",
      name: "科学原理",
      accent: "glacier",
      description: "拆解训练适应、恢复窗口、能量系统和长期进步背后的核心逻辑。",
    },
    {
      id: "rehab",
      name: "运动康复",
      accent: "lime",
      description: "面向肩、膝、髋和脊柱常见问题，整理动作控制、活动度与恢复策略。",
    },
    {
      id: "nutrition",
      name: "营养指南",
      accent: "sun",
      description: "聚焦热量、蛋白质、补水、电解质和日常饮食结构，让营养建议更容易执行。",
    },
  ],
  posts: [
    {
      id: "strength-bench-001",
      title: "卧推总是肩膀先酸？先检查这 3 个细节",
      category: "strength",
      type: "article",
      summary: "从肩胛稳定、握距与肘部路径切入，解释为什么很多人的卧推刺激没有真正落在胸部。",
      content: [
        {
          heading: "先让肩胛稳定下来",
          body: "如果上背没有主动收紧，卧推时肩关节就容易抢动作。先把肩胛向后向下固定，再让胸廓稳定，发力路径会更清晰。",
        },
        {
          heading: "握距不是越宽越好",
          body: "过宽握距会让肩前侧压力明显上升，很多人为了追求胸部感觉反而失去控制。更适合的做法是让前臂在底部接近垂直，保持推起时的稳定杠铃路线。",
        },
        {
          heading: "肘部路径决定受力分配",
          body: "肘部外展过大时，肩膀会更容易主导动作。把肘部控制在更自然的夹角，并让杠铃落点稳定在中下胸附近，通常更容易把刺激留在胸部和肱三头。",
        },
      ],
      takeaways: ["先稳住上背再发力", "用可控制的握距而不是盲目加宽", "让肘部和杠铃路径保持一致"],
      image: "",
      tags: ["卧推", "胸部发力", "动作技术"],
      featured: true,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-strength-bench-001",
    },
    {
      id: "cardio-bili-001",
      title: "跑步配速怎么判断，才不会一开始就崩",
      category: "cardio",
      type: "video",
      summary: "适合新手理解轻松跑、节奏跑与间歇跑的区别，也适合放入任意平台的视频讲解链接。",
      image: "",
      tags: ["跑步", "配速", "心肺训练"],
      featured: true,
      readTime: "视频",
      ctaLabel: "打开视频",
      ctaUrl: "https://example.com/video/cardio-pace",
    },
    {
      id: "science-001",
      title: "为什么训练后没有酸痛，不代表白练了",
      category: "science",
      type: "article",
      summary: "延迟性肌肉酸痛只是训练反应的一部分，真正决定长期进步的是刺激质量、恢复与持续性。",
      content: [
        {
          heading: "酸痛不是进步凭证",
          body: "酸痛更像是一次陌生刺激后的反应，而不是训练有效性的唯一证明。动作变化、离心量增加或恢复不足，都可能让酸痛更明显。",
        },
        {
          heading: "真正重要的是刺激质量",
          body: "目标肌群有没有得到足够张力、动作是否稳定、训练量是否处在合理区间，这些才更接近长期增长和适应的核心因素。",
        },
        {
          heading: "恢复决定你能不能继续进步",
          body: "睡眠、饮食和训练安排共同决定下一次训练质量。没有酸痛但能稳定完成计划、表现逐步提升，通常比一味追求酸痛更可靠。",
        },
      ],
      takeaways: ["别把酸痛当成唯一指标", "看动作质量和训练表现", "恢复能力会影响下一次进步"],
      image: "",
      tags: ["训练适应", "恢复", "误区"],
      featured: false,
      readTime: "5 分钟",
      ctaLabel: "查看内容",
      ctaUrl: "#post-science-001",
    },
    {
      id: "rehab-001",
      title: "久坐后髋部很紧，先别急着猛拉伸",
      category: "rehab",
      type: "article",
      summary: "很多髋部僵硬不只是长度问题，也涉及控制能力与代偿模式，恢复内容要先重新组织动作。",
      content: [
        {
          heading: "紧不一定代表短",
          body: "长时间坐姿会让髋部习惯某种姿态，但主观上的紧绷感并不一定意味着组织真的缩短，很多时候是身体在提醒你缺少主动控制。",
        },
        {
          heading: "先恢复控制，再追求幅度",
          body: "比起一开始就大幅度拉伸，更实用的方式是先做轻负荷的髋屈伸、骨盆控制和单腿稳定练习，让身体重新认识这个活动范围。",
        },
        {
          heading: "把恢复动作接回日常",
          body: "如果久坐模式不改变，单次拉伸效果通常维持不久。站立间隙、走动频率和简单激活练习，往往比一次性猛拉更有帮助。",
        },
      ],
      takeaways: ["髋紧常常和控制有关", "恢复训练先求可控", "把活动频率放回日常习惯里"],
      image: "",
      tags: ["髋部", "久坐", "恢复"],
      featured: true,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-rehab-001",
    },
    {
      id: "nutrition-bili-001",
      title: "蛋白质怎么吃，才更适合训练人群",
      category: "nutrition",
      type: "video",
      summary: "把总量、分配频率和真实饮食场景结合起来讲，更适合做长期更新的视频专题入口。",
      image: "",
      tags: ["蛋白质", "增肌", "饮食结构"],
      featured: false,
      readTime: "视频",
      ctaLabel: "打开视频",
      ctaUrl: "https://example.com/video/protein-guide",
    },
    {
      id: "strength-plan-002",
      title: "一周三练，怎样安排推拉腿才不混乱",
      category: "strength",
      type: "article",
      summary: "适合放成系列文章，帮助读者理解频率、动作选择和恢复优先级之间的平衡。",
      content: [
        {
          heading: "先明确每次训练的主任务",
          body: "一周只有三次训练时，每天都需要有鲜明重点。推日关注水平和垂直推，拉日聚焦背部与肱二头，腿日则把下肢力量和稳定性放到核心位置。",
        },
        {
          heading: "动作选择不要贪多",
          body: "每次训练选 4 到 6 个关键动作通常就够了。基础复合动作承担主要负荷，辅助动作用来补足薄弱环节，而不是把每个部位都塞满。",
        },
        {
          heading: "恢复优先级要写进计划",
          body: "如果工作和生活压力较大，训练安排就要给恢复留空间。宁可把总量做得可持续，也不要让连续疲劳打乱整个周期。",
        },
      ],
      takeaways: ["每次训练先定主线", "动作数量少而精", "训练计划要和恢复能力匹配"],
      image: "",
      tags: ["训练计划", "推拉腿", "一周三练"],
      featured: false,
      readTime: "6 分钟",
      ctaLabel: "查看内容",
      ctaUrl: "#post-strength-plan-002",
    },
  ],
};
