window.siteData = {
  siteName: "向老师的FitPulse Lab",
  siteTagline: "健身科普内容站",
  heroEyebrow: "Strength. Engine. Recovery.",
  heroTitle: "把训练、恢复和营养，讲成真正能改变习惯的知识。",
  heroDescription:
    "围绕力量训练、有氧训练、运动康复、营养指南和健身科学原理，持续整理更清晰、更可信、更容易执行的健身科普内容。",
  footerText: "训练不是碎片化打卡，而是长期认知与习惯的建立。",
  categories: [
    {
      id: "strength",
      name: "力量训练",
      accent: "ember",
      image: "./images/strength-category-cover.png",
      description: "围绕动作技术、训练计划、容量安排和渐进超负荷，帮助读者真正理解怎么练得更稳、更强。",
    },
    {
      id: "cardio",
      name: "有氧训练",
      accent: "volt",
      image: "./images/cardio-category-cover.png",
      description: "关注心肺能力、跑步节奏、间歇训练和日常耐力表现，让有氧不再只是“多跑一点”。",
    },
    {
      id: "science",
      name: "健身科学原理",
      accent: "glacier",
      image: "./images/science-category-cover.png",
      description: "拆解训练适应、恢复窗口、能量系统和长期进步背后的核心逻辑。",
    },
    {
      id: "rehab",
      name: "运动康复",
      accent: "lime",
      image: "./images/rehab-category-cover.png",
      description: "面向肩、膝、髋和脊柱常见问题，整理动作控制、活动度与恢复策略。",
    },
    {
      id: "nutrition",
      name: "营养指南",
      accent: "sun",
      image: "./images/nutrition-category-cover.png",
      description: "聚焦热量、蛋白质、补水、电解质和日常饮食结构，让营养建议更容易执行。",
    },
  ],
  posts: [
    {
      id: "strength-article-001",
      title: "新手如何开始力量训练",
      category: "strength",
      type: "article",
      summary: "介绍力量训练的基础动作、训练频率和入门注意事项。",
      content: "新手开始力量训练时，最重要的不是一上来追求大重量，而是先建立正确动作模式和稳定训练习惯。建议从深蹲、俯卧撑、臀桥、划船、平板支撑等基础动作入手，这些动作可以覆盖下肢、上肢、臀部和核心肌群。刚开始每周训练2到3次即可，每次控制在40到60分钟。训练前要进行动态热身，训练中注意呼吸、节奏和动作控制，不要为了完成次数而牺牲姿势。前4到6周可以重点学习动作，逐步增加训练量。只要坚持记录训练内容，循序渐进增加次数、组数或阻力，就能安全提升力量和体能。",
      image: "./images/strength-category-cover.png",
      tags: ["入门", "基础动作", "训练习惯"],
      featured: true,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-strength-article-001",
    },
    {
      id: "strength-article-002",
      title: "增肌训练的核心：渐进超负荷",
      category: "strength",
      type: "article",
      summary: "解释如何通过增加重量、次数、组数来持续进步。",
      content: "增肌训练的核心原则是渐进超负荷，也就是让肌肉在可承受范围内持续接受更高水平的刺激。超负荷不一定只代表加重量，也可以通过增加次数、增加组数、放慢离心速度、缩短休息时间或提高动作质量来实现。例如本周某个动作能完成3组10次，下周可以尝试增加到3组12次，或者保持次数不变但略微增加重量。需要注意的是，渐进并不等于每次训练都必须突破极限，过度追求力竭反而容易影响恢复。合理的增肌训练应在动作标准的基础上逐步增加难度，同时配合足够蛋白质、总热量和睡眠。训练、营养和恢复三者结合，才能形成稳定的肌肉增长。",
      image: "./images/strength-category-cover.png",
      tags: ["增肌", "渐进超负荷", "训练计划"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-strength-article-002",
    },
    {
      id: "strength-article-003",
      title: "核心训练不只是练腹肌",
      category: "strength",
      type: "article",
      summary: "讲解核心稳定对运动表现和腰背保护的重要性。",
      content: "很多人把核心训练理解为卷腹或练出腹肌，但真正的核心能力更强调躯干稳定和力量传递。核心肌群包括腹直肌、腹横肌、腹斜肌、竖脊肌、骨盆周围肌群以及髋部稳定肌群。它们在深蹲、硬拉、跑步、跳跃和日常搬重物时都会参与工作。强大的核心可以帮助身体保持稳定，减少腰椎代偿，提高动作效率。相比大量卷腹，更建议加入平板支撑、死虫、鸟狗、侧桥、农夫行走和抗旋转训练。这些动作可以训练身体在不同姿势下保持控制。核心训练不只是为了外形，更是保护腰背、提升运动表现和改善姿态的重要基础。",
      image: "./images/strength-category-cover.png",
      tags: ["核心", "稳定", "腰背保护"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-strength-article-003",
    },
    {
      id: "strength-article-004",
      title: "如何避免力量训练受伤",
      category: "strength",
      type: "article",
      summary: "介绍热身、动作标准、负荷控制和恢复原则。",
      content: "力量训练受伤通常不是单一原因造成的，而是热身不足、动作不稳定、负荷增长过快、疲劳积累和恢复不足共同作用的结果。训练前应先进行5到10分钟动态热身，再用轻重量完成专项准备，让关节和肌肉逐渐进入状态。正式训练时，应优先保证动作质量，而不是盲目追求重量。如果出现关节刺痛、动作明显变形或身体失去控制，应立即降低重量或停止该动作。训练计划也要安排恢复时间，同一肌群不宜每天高强度刺激。睡眠不足、饮食不足和长期压力过大都会增加受伤风险。安全训练的关键是循序渐进、技术优先、及时调整，而不是用意志硬撑。",
      image: "./images/strength-category-cover.png",
      tags: ["受伤预防", "热身", "恢复"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-strength-article-004",
    },
    {
      id: "strength-article-005",
      title: "居家力量训练怎么练",
      category: "strength",
      type: "article",
      summary: "设计无器械或少器械的居家力量训练思路。",
      content: "居家力量训练不一定需要复杂器械，只要安排合理，自重、弹力带和一对哑铃也能完成有效训练。居家训练可以选择深蹲、弓步蹲、臀桥、俯卧撑、弹力带划船、肩推、平板支撑等动作，覆盖腿、臀、胸、背、肩和核心。每次训练可以选择5到7个动作，每个动作完成3到4组，每组8到15次。没有大重量时，可以通过放慢动作速度、增加停顿、提高次数或减少休息时间来增加难度。居家训练还要注意空间安全，避免地面打滑或动作幅度受限。只要保持规律训练和逐步进阶，即使不去健身房，也能有效提升力量、改善体态和增强身体控制能力。",
      image: "./images/strength-category-cover.png",
      tags: ["居家训练", "自重", "哑铃"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-strength-article-005",
    },
    {
      id: "cardio-article-001",
      title: "有氧训练到底练什么",
      category: "cardio",
      type: "article",
      summary: "介绍心肺耐力、脂肪代谢和健康收益。",
      content: "有氧训练主要锻炼心肺功能、耐力水平和身体持续供能能力。常见有氧运动包括快走、慢跑、骑车、游泳、椭圆机、划船机和跳绳。规律进行有氧训练，可以提高心脏泵血能力，改善血液循环，增强身体利用氧气的效率，同时帮助增加日常能量消耗。对于减脂人群来说，有氧训练不是唯一方法，但它可以与力量训练和饮食控制形成良好配合。新手不需要一开始就做高强度训练，可以从每周3次、每次20到30分钟开始，强度控制在微微喘气但还能说完整句话的程度。长期坚持比短期大量训练更重要，稳定的有氧习惯有助于提升健康水平和运动能力。",
      image: "./images/cardio-category-cover.png",
      tags: ["心肺", "耐力", "减脂"],
      featured: true,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-cardio-article-001",
    },
    {
      id: "cardio-article-002",
      title: "有氧和力量训练先做哪个",
      category: "cardio",
      type: "article",
      summary: "根据增肌、减脂、体能提升目标进行安排。",
      content: "有氧和力量训练的先后顺序，应根据个人目标来决定。如果主要目标是增肌或提高力量，建议先做力量训练，再进行低到中等强度有氧，因为力量训练需要更好的肌肉状态和神经兴奋度。如果先进行长时间高强度有氧，可能会影响后续力量动作质量。若目标是减脂，可以采用力量训练后加有氧的方式，既能通过力量训练保留肌肉，也能通过有氧增加能量消耗。如果目标是提高跑步、骑行等专项能力，则应把有氧训练放在主要位置。无论顺序如何，都要注意总训练量和恢复情况。训练不是越多越好，关键是让训练安排服务于目标，并保证动作质量和长期坚持。",
      image: "./images/cardio-category-cover.png",
      tags: ["训练顺序", "减脂", "增肌"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-cardio-article-002",
    },
    {
      id: "cardio-article-003",
      title: "心率区间怎么看",
      category: "cardio",
      type: "article",
      summary: "解释燃脂心率、最大心率和训练强度区间。",
      content: "心率是判断有氧训练强度的一个实用指标。一般可以用220减去年龄来粗略估算最大心率，然后根据最大心率比例划分不同训练区间。低强度区间适合恢复、热身和基础耐力训练；中等强度区间适合提高心肺能力和脂肪代谢能力；高强度区间则常用于间歇训练和运动表现提升。很多人关注所谓燃脂心率，但需要理解的是，燃脂心率并不代表只有这个区间才会消耗脂肪。减脂的关键仍然是长期热量消耗大于摄入。心率区间的作用是帮助控制训练强度，避免训练过轻没有刺激，或过强导致疲劳过度。对于新手来说，先建立稳定的中低强度有氧习惯更安全。",
      image: "./images/cardio-category-cover.png",
      tags: ["心率", "强度", "有氧"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-cardio-article-003",
    },
    {
      id: "cardio-article-004",
      title: "HIIT适合所有人吗",
      category: "cardio",
      type: "article",
      summary: "讲解高强度间歇训练的优势、风险和适用人群。",
      content: "HIIT是高强度间歇训练，通常由短时间高强度运动和短暂休息交替组成，例如冲刺跑、波比跳、登山跑和跳绳间歇。它的优点是时间短、刺激强，可以提高心肺能力和运动消耗。但HIIT并不适合所有人，尤其是训练基础较弱、体重较大、膝踝关节不适或心肺功能较差的人，盲目进行高冲击HIIT可能增加受伤风险。新手更适合先从快走、骑车、椭圆机等低冲击有氧开始，逐渐提高体能后再尝试间歇训练。即使是有训练经验的人，HIIT也不宜每天做，每周1到2次即可。高强度训练需要更充分的热身和恢复，不能只看燃脂效果而忽视身体承受能力。",
      image: "./images/cardio-category-cover.png",
      tags: ["HIIT", "间歇训练", "风险"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-cardio-article-004",
    },
    {
      id: "cardio-article-005",
      title: "如何提高跑步耐力",
      category: "cardio",
      type: "article",
      summary: "介绍跑步耐力提升的训练方法和节奏控制。",
      content: "提高跑步耐力的关键不是每次都拼速度，而是循序渐进地增加身体对持续运动的适应能力。新手可以采用跑走结合的方法，例如慢跑2分钟、快走1分钟，重复20到30分钟。随着心肺能力提高，再逐渐延长连续慢跑时间。跑步时配速要保持稳定，不要一开始太快，否则很容易后程乏力。每周跑步2到4次比较合适，同时安排至少1天恢复。想要跑得更远，还需要注意下肢力量、核心稳定和踝膝髋关节控制。跑前做好动态热身，跑后进行放松和拉伸，可以减少小腿紧张和膝盖不适。耐力提升是长期积累的过程，稳定训练比偶尔一次高强度更有效。",
      image: "./images/cardio-category-cover.png",
      tags: ["跑步", "耐力", "配速"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-cardio-article-005",
    },
    {
      id: "rehab-article-001",
      title: "久坐导致腰背酸痛怎么办",
      category: "rehab",
      type: "article",
      summary: "介绍久坐人群常见腰背问题与改善方法。",
      content: "久坐人群出现腰背酸痛很常见，原因通常不是单纯腰部力量差，而是髋屈肌紧张、臀部肌群激活不足、核心稳定下降和胸椎活动受限共同造成的。长时间坐姿会让骨盆和腰椎长期处于固定位置，久而久之容易产生不适。改善时不能只依赖按摩或贴膏药，而要通过训练恢复身体控制。可以每天进行髋屈肌拉伸、臀桥、鸟狗、猫牛式、胸椎旋转和死虫训练，帮助放松紧张区域并激活薄弱肌群。工作时建议每45到60分钟起身活动几分钟，改变久坐姿势。如果腰痛伴随腿麻、放射痛、明显无力或持续加重，应及时找医生或康复专业人员评估。",
      image: "./images/rehab-category-cover.png",
      tags: ["腰背", "久坐", "恢复"],
      featured: true,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-rehab-article-001",
    },
    {
      id: "rehab-article-002",
      title: "运动前热身为什么重要",
      category: "rehab",
      type: "article",
      summary: "讲解动态热身对关节活动度和损伤预防的作用。",
      content: "运动前热身不是简单活动几下，也不是只为了出汗，而是让身体从静息状态逐渐进入训练状态。有效热身可以提高体温，增加关节滑液分泌，改善肌肉弹性和关节活动度，同时激活神经系统，让动作反应更快、更稳定。热身应根据训练内容选择，如果要练下肢，可以加入开合跳、弓步转体、髋部绕环和徒手深蹲；如果要练上肢，可以加入肩部环绕、弹力带外旋和俯卧撑准备组。热身时间一般为5到15分钟，强度逐渐上升。训练负荷越大、动作越复杂，热身越不能省略。良好的热身可以减少突然发力造成的损伤，也能提升正式训练表现。",
      image: "./images/rehab-category-cover.png",
      tags: ["热身", "关节活动度", "损伤预防"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-rehab-article-002",
    },
    {
      id: "rehab-article-003",
      title: "膝盖疼还能不能运动",
      category: "rehab",
      type: "article",
      summary: "介绍膝关节不适时的运动原则和注意事项。",
      content: "膝盖疼时是否可以运动，要看疼痛程度、出现位置和诱发动作。轻微不适并不意味着必须完全停止活动，但需要避免加重疼痛的动作，例如频繁跳跃、深度蹲起或高强度跑步。可以选择低冲击训练，如快走、骑车、椭圆机、臀桥、靠墙静蹲和弹力带侧步。训练时要观察膝盖是否内扣、脚掌是否稳定、髋部是否参与发力。很多膝痛问题与臀部力量不足、踝关节活动差或动作控制不佳有关，不一定只是膝盖本身的问题。如果疼痛明显、伴随肿胀、卡住感、走路困难或持续多天不缓解，应暂停高强度训练并寻求专业评估。运动康复的原则是减轻刺激、恢复控制、逐步回归。",
      image: "./images/rehab-category-cover.png",
      tags: ["膝关节", "疼痛", "低冲击"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-rehab-article-003",
    },
    {
      id: "rehab-article-004",
      title: "圆肩驼背怎么改善",
      category: "rehab",
      type: "article",
      summary: "从胸肌紧张、背部无力和姿势习惯角度分析改善方法。",
      content: "圆肩驼背常见于长期伏案、低头看手机和缺乏上背部训练的人群。它通常与胸肌紧张、胸椎伸展能力不足、肩胛骨控制差和背部肌群薄弱有关。改善圆肩驼背不能只靠提醒自己坐直，因为肌肉力量和关节活动度如果没有改善，很快又会回到原来的姿势。训练上可以加入胸肌拉伸、泡沫轴胸椎伸展、弹力带划船、面拉、肩胛后缩和墙天使等动作。日常工作时，应调整屏幕高度，减少长时间低头，每隔一段时间活动肩颈和上背。改善体态需要长期积累，不是一次拉伸就能解决。只要坚持放松紧张肌群、强化背部和建立良好习惯，圆肩驼背会逐渐改善。",
      image: "./images/rehab-category-cover.png",
      tags: ["体态", "圆肩", "上背"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-rehab-article-004",
    },
    {
      id: "rehab-article-005",
      title: "跑步后小腿紧张怎么恢复",
      category: "rehab",
      type: "article",
      summary: "介绍跑后小腿紧张的放松和恢复方法。",
      content: "跑步后小腿紧张很常见，可能与训练量突然增加、跑步速度过快、步频不稳定、踝关节活动度不足或小腿过度代偿有关。如果每次跑后小腿都特别紧，说明身体可能还没有适应当前训练强度。恢复时可以先进行低强度走路，让身体慢慢降温，再进行腓肠肌和比目鱼肌拉伸。泡沫轴放松小腿后侧和足底筋膜，也有助于缓解紧张感。下次跑步前，应加强踝关节活动、臀部激活和小腿动态热身，避免一上来就快速跑。跑步训练量应逐步增加，不建议突然提升距离或速度。如果小腿出现局部刺痛、肿胀或按压疼痛明显，应减少训练并及时检查，避免发展成更严重的损伤。",
      image: "./images/rehab-category-cover.png",
      tags: ["小腿", "跑步恢复", "拉伸"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-rehab-article-005",
    },
    {
      id: "nutrition-article-001",
      title: "减脂期怎么吃才不容易反弹",
      category: "nutrition",
      type: "article",
      summary: "介绍热量缺口、蛋白质摄入和长期饮食习惯。",
      content: "减脂的核心是建立适度热量缺口，但不建议长期采用极端节食。热量过低虽然短期体重下降快，但容易导致饥饿感增强、训练状态下降、基础活动减少，后期反弹风险也更高。更稳定的方式是控制总热量，同时保证蛋白质摄入和食物质量。减脂期可以多选择鸡蛋、鱼肉、瘦肉、牛奶、豆制品等优质蛋白，搭配足量蔬菜和适量主食。碳水不需要完全戒掉，训练日尤其需要碳水提供能量。饮食结构应尽量简单、规律、可长期坚持，而不是依靠短期意志力硬撑。真正不容易反弹的减脂，是在体重下降的同时建立新的生活方式，包括规律运动、稳定作息和合理饮食。",
      image: "./images/nutrition-category-cover.png",
      tags: ["减脂", "热量缺口", "蛋白质"],
      featured: true,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-nutrition-article-001",
    },
    {
      id: "nutrition-article-002",
      title: "训练前吃什么更有力气",
      category: "nutrition",
      type: "article",
      summary: "介绍训练前的饮食选择和能量补充原则。",
      content: "训练前饮食的目标是提供稳定能量，同时避免胃部不适。一般来说，训练前1到2小时可以吃一些容易消化的碳水和少量蛋白质，例如香蕉、燕麦、全麦面包、酸奶、鸡蛋、米饭或土豆。如果距离训练时间很近，可以选择一根香蕉或少量运动饮料，避免吃太油腻或太难消化的食物。力量训练和高强度有氧都需要糖原支持，长期空腹进行高强度训练可能导致乏力、头晕或训练质量下降。当然，每个人消化速度不同，训练前吃多少要根据自身感受调整。理想状态是训练时既不饿，也不撑，身体有足够能量完成高质量动作。",
      image: "./images/nutrition-category-cover.png",
      tags: ["训练前饮食", "碳水", "能量"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-nutrition-article-002",
    },
    {
      id: "nutrition-article-003",
      title: "增肌期为什么要吃够蛋白质",
      category: "nutrition",
      type: "article",
      summary: "讲解蛋白质对肌肉修复和增长的重要性。",
      content: "蛋白质是肌肉修复和增长的重要原料。力量训练会对肌肉产生刺激，身体需要在训练后通过营养和休息进行修复，如果蛋白质长期不足，肌肉增长和恢复都会受到影响。增肌期可以优先选择鸡蛋、牛奶、酸奶、鱼肉、鸡胸肉、牛肉、虾、豆腐和豆制品等优质蛋白。蛋白质摄入最好分散到一天多餐中，而不是全部集中在一顿。除了蛋白质，增肌还需要足够总热量和碳水，因为碳水可以支持训练表现，脂肪也参与激素和健康维持。只补蛋白粉但训练不足，或者训练很努力但总热量不够，都很难获得理想增肌效果。增肌是训练、营养和恢复共同作用的结果。",
      image: "./images/nutrition-category-cover.png",
      tags: ["增肌", "蛋白质", "恢复"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-nutrition-article-003",
    },
    {
      id: "nutrition-article-004",
      title: "碳水是不是减脂的敌人",
      category: "nutrition",
      type: "article",
      summary: "解释碳水在训练表现和减脂中的作用。",
      content: "碳水并不是减脂的敌人，真正决定体脂变化的是长期总热量平衡。很多人减脂时把米饭、面条、馒头完全戒掉，短期体重可能下降较快，但其中一部分来自水分和糖原减少，并不等于脂肪大量减少。碳水是运动时重要的能量来源，尤其是力量训练、跑步、骑车和高强度间歇训练，都需要糖原支持。完全不吃碳水可能导致训练状态下降、情绪不稳定、饥饿感增强，甚至增加暴食风险。减脂期更合理的做法是选择优质碳水并控制总量，例如米饭、燕麦、土豆、玉米、全麦面包和杂粮。碳水不是问题，过量摄入和缺乏运动才是更常见的问题。",
      image: "./images/nutrition-category-cover.png",
      tags: ["碳水", "减脂", "训练表现"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-nutrition-article-004",
    },
    {
      id: "nutrition-article-005",
      title: "如何看懂食物营养标签",
      category: "nutrition",
      type: "article",
      summary: "教用户识别热量、蛋白质、脂肪、糖和钠含量。",
      content: "看懂营养标签可以帮助你更准确地控制饮食。首先要看每份含量和总份数，很多包装食品看起来热量不高，但一整袋可能包含两份甚至多份，实际摄入要乘以份数。其次看能量、蛋白质、脂肪、碳水、糖和钠含量。减脂人群应特别注意高糖、高脂和高热量密度食品；增肌人群则可以关注蛋白质含量是否足够。钠含量过高的食品容易导致水肿和口渴，也不适合长期大量摄入。不要只看包装正面的“低脂”“粗粮”“高蛋白”等宣传语，真正有参考价值的是配料表和营养成分表。学会看标签，不是为了让饮食变得复杂，而是帮助自己做出更清楚的选择。",
      image: "./images/nutrition-category-cover.png",
      tags: ["营养标签", "热量", "配料表"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-nutrition-article-005",
    },
    {
      id: "science-article-001",
      title: "减脂的本质是什么",
      category: "science",
      type: "article",
      summary: "从能量平衡角度解释减脂的核心逻辑。",
      content: "减脂的本质是长期能量消耗大于能量摄入，也就是形成热量缺口。身体每天都会消耗能量，包括基础代谢、日常活动、运动消耗和食物消化消耗。当摄入能量长期低于消耗时，身体会逐渐动用储存脂肪来补充能量。运动可以增加消耗，饮食控制可以减少摄入，两者结合通常比单独节食更稳定。需要注意的是，体重短期波动并不完全代表脂肪变化，水分、糖原、盐分、月经周期和肠道内容物都会影响体重。判断减脂效果时，不应只看一天的数字，而要看几周趋势，同时结合腰围、照片和训练表现。科学减脂不是越快越好，而是尽可能保留肌肉、减少反弹并形成可持续习惯。",
      image: "./images/science-category-cover.png",
      tags: ["减脂", "能量平衡", "热量缺口"],
      featured: true,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-science-article-001",
    },
    {
      id: "science-article-002",
      title: "训练后为什么会酸痛",
      category: "science",
      type: "article",
      summary: "讲解延迟性肌肉酸痛和恢复机制。",
      content: "训练后肌肉酸痛通常被称为延迟性肌肉酸痛，常出现在训练后24到48小时，尤其是在尝试新动作、提高训练强度或进行较多离心收缩后更明显。酸痛与肌肉微损伤、炎症反应和身体修复过程有关，但酸痛并不等于训练一定有效，也不是增肌的唯一标准。有些训练虽然不酸，但仍然可以带来进步；相反，过度酸痛可能影响下一次训练质量。恢复时可以进行低强度活动、轻度拉伸、补充蛋白质和碳水，并保证睡眠。如果某个部位酸痛严重，不建议继续高强度训练同一肌群。需要区分正常肌肉酸痛和损伤疼痛，若出现关节刺痛、肿胀或活动受限，应及时停止训练并评估。",
      image: "./images/science-category-cover.png",
      tags: ["酸痛", "恢复", "DOMS"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-science-article-002",
    },
    {
      id: "science-article-003",
      title: "为什么体重不变但身材变好了",
      category: "science",
      type: "article",
      summary: "解释体脂下降、肌肉增加和身体成分变化。",
      content: "体重不变并不代表训练没有效果，因为体重只是身体总重量，并不能区分脂肪、肌肉、水分和糖原。力量训练和合理饮食可能让肌肉量增加、体脂下降，身体围度和线条发生变化，但体重数字变化并不明显。这种情况在新手、恢复训练者和减脂塑形人群中很常见。相比只看体重，更建议同时观察腰围、臀围、照片对比、衣服松紧、训练重量和精神状态。如果腰围变小、力量提升、体态更好，即使体重没有明显下降，也说明身体成分正在改善。单纯追求掉秤可能导致过度节食和肌肉流失，而身体成分改善往往更能体现真实健康和外形变化。健身不只是减轻体重，更是提升身体质量。",
      image: "./images/science-category-cover.png",
      tags: ["身体成分", "体脂", "塑形"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-science-article-003",
    },
    {
      id: "science-article-004",
      title: "肌肉是怎么增长的",
      category: "science",
      type: "article",
      summary: "解释肌肉增长与训练刺激、营养恢复之间的关系。",
      content: "肌肉增长来自训练刺激、营养补充和充分恢复的共同作用。力量训练会给肌肉带来机械张力和代谢刺激，身体在恢复过程中修复并增强肌肉组织，从而适应下一次训练。想要持续增肌，需要让训练具有一定挑战性，例如逐步增加重量、次数、组数或动作难度。与此同时，身体需要足够蛋白质和总热量作为修复材料和能量来源。如果训练很努力但吃得太少，肌肉增长会受到限制；如果只吃很多但缺乏有效训练，增加的可能更多是脂肪。睡眠同样重要，因为恢复和激素调节很大程度发生在休息阶段。增肌不是某一次训练的结果，而是长期重复“刺激—恢复—适应”的过程。",
      image: "./images/science-category-cover.png",
      tags: ["增肌", "恢复", "适应"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-science-article-004",
    },
    {
      id: "science-article-005",
      title: "训练平台期是怎么来的",
      category: "science",
      type: "article",
      summary: "分析训练停滞的原因和突破思路。",
      content: "训练平台期是指力量、围度、体重或运动表现一段时间内进步变慢甚至停滞。它通常不是突然发生的，而是身体已经适应了当前训练刺激。常见原因包括训练计划长期不变、负荷不足、训练量过低或过高、恢复不充分、睡眠质量差、饮食摄入不足等。突破平台期可以先回顾训练记录，判断是刺激不够还是疲劳过多。如果刺激不足，可以增加训练重量、组数或改变动作；如果疲劳过多，则需要安排减量周，减少训练量，让身体恢复。营养上也要检查蛋白质和总热量是否足够。平台期并不可怕，它是身体适应过程中的正常阶段。通过调整训练、饮食和恢复，大多数人都可以重新获得进步。",
      image: "./images/science-category-cover.png",
      tags: ["平台期", "训练调整", "恢复"],
      featured: false,
      readTime: "4 分钟",
      ctaLabel: "阅读内容",
      ctaUrl: "#post-science-article-005",
    },
  ],
};
